# Generated by Django 2.2.3 on 2020-11-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartendish', '0005_auto_20200622_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='calories',
        ),
    ]
