# Generated by Django 2.2.3 on 2020-11-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartendish', '0006_remove_composition_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergartendish',
            name='allergens',
            field=models.TextField(blank=True, null=True, verbose_name='Allergens in the dish'),
        ),
        migrations.AddField(
            model_name='kindergartendish',
            name='calories',
            field=models.FloatField(blank=True, null=True, verbose_name='Calories per portion'),
        ),
        migrations.AlterField(
            model_name='kindergartendish',
            name='waste',
            field=models.CharField(blank=True, choices=[('less5', 'Less than 5 %'), ('5to10', 'From 5 % to 10 %'), ('11to25', 'From 11 % to 25 %'), ('more25', 'More than 25 %')], max_length=6, null=True, verbose_name='What percentage of food becomes waste during food preparation?'),
        ),
    ]
