# Generated by Django 2.2.3 on 2020-12-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartendish', '0008_auto_20201202_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergartendish',
            name='type',
            field=models.CharField(blank=True, choices=[('breakfast_en', 'Breakfast'), ('lunch_en', 'Lunch'), ('afternoon_tea_en', 'Afternoon tea'), ('breakfast_pl', 'Śniadanie'), ('lunch_pl', 'Obiad'), ('afternoon_tea_pl', 'Podwieczorek')], max_length=16, null=True, verbose_name='Type of meal'),
        ),
        migrations.AlterField(
            model_name='kindergartendish',
            name='waste',
            field=models.CharField(blank=True, choices=[('less5_en', 'Less than 5 %'), ('5to10_en', 'From 5 % to 10 %'), ('11to25_en', 'From 11 % to 25 %'), ('more25_en', 'More than 25 %'), ('less5_pl', 'mniej niż 5 %'), ('5to10_pl', 'od 5 % do 10 %'), ('11to25_pl', 'od 11 % do 25 %'), ('more25_pl', 'więcej niż 25 %')], max_length=9, null=True, verbose_name='What percentage of food becomes waste during food preparation?'),
        ),
    ]
