# Generated by Django 2.2.3 on 2021-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergartendish', '0009_auto_20201202_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='from_producer',
            field=models.CharField(blank=True, choices=[('local', 'Produkt lokalny (ze Słupska lub okolic w granicach 100 km)'), ('regional', 'Produkt regionalny (z województwa pomorskiego)'), ('national', 'Produkt krajowy'), ('foreign', 'Produkt zagraniczny'), ('uncertain', 'Nie wiem')], max_length=9, null=True, verbose_name='Was the ingredient bought directly from the producer?'),
        ),
    ]
