# Generated by Django 2.2.3 on 2019-12-17 16:37

from django.db import migrations


def insertData(apps, schema_editor):
     Ingredient = apps.get_model('ingredient', 'Ingredient')
     ingredient = Ingredient(name = "Cabbage")
     ingredient.save()
     ingredient = Ingredient(name = "Chicken meat")
     ingredient.save()
     ingredient = Ingredient(name = "Cucumber")
     ingredient.save()
     ingredient = Ingredient(name = "Egg")
     ingredient.save()
     ingredient = Ingredient(name = "Onion")
     ingredient.save()
     ingredient = Ingredient(name = "Potatoe")
     ingredient.save()
     ingredient = Ingredient(name = "Tomatoe")
     ingredient.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
