# Generated by Django 2.2.3 on 2020-02-21 12:34

from django.db import migrations

def insertData(apps, schema_editor):
    Shop = apps.get_model('shop', 'Shop')
    shop = Shop(name = "ADKONIS Ferma Kur", type = "Lokalna ferma kur", product = "Jajka, mięso z kurczaka", address = "Słupska 1, 76-251 Kobylnica", phone = "603 601 611, 731 093 345", email = "-", website = "http://ferma.adkonis.pl/company.php", toggle = "manual", latitude = 54.370454, longitude = 17.022231, accuracy=250)
    shop.save()
    shop = Shop(name = "ANMAR Przedsiębiorstwo Handlowe Wioletta i Czesław Kazimierczak", type = "Hurtownia", product = "Owoce i warzywa mrożone", address = "Witolda Lutosławskiego 18, 76-200 Słupsk", phone = "(59) 842 60 13", email = "-", website = "-", toggle = "manual", latitude = 54.458251, longitude = 17.026484, accuracy=250)
    shop.save()
    shop = Shop(name = "DOMIN Piotr Kryga", type = "Piekarnia", product = "Chleb i wypieki", address = "Kościelna 33, 76-248 Dębnica Kaszubska", phone = "602 117 090", email = "biuro@domin.com.pl", website = "http://www.domin.com.pl", toggle = "manual", latitude = 54.375420, longitude = 17.158350, accuracy=250)
    shop.save()
    shop = Shop(name = "EUFORIAFRUIT Jacek Giez", type = "Hurtownia", product = "Owoce, warzywa", address = "Poznańska 98, 76-200 Słupsk", phone = "-", email = "-", website = "-", toggle = "manual", latitude = 54.456749, longitude = 17.024326, accuracy=250)
    shop.save()
    shop = Shop(name = "FAMILY-ICE Firma Handlowa Grzegorz Szczepański", type = "Hurtownia", product = "Owoce i warzywa mrożone", address = "Wodna 15, 76-251 Kobylnica", phone = "(59) 841 54 15", email = "familyice@onet.eu", website = "-", toggle = "manual", latitude = 54.440167, longitude = 17.015746, accuracy=250)
    shop.save()
    shop = Shop(name = "Firma Handlowo Usługowa Paweł Drewicz", type = "Hurtownia", product = "Artykuły spożywcze", address = "Kamila Norwida 12, 76-200 Słupsk", phone = "(59) 843 84 05", email = "paweldre@gmail.com", website = "-", toggle = "manual", latitude = 54.464505, longitude = 16.996877, accuracy=250)
    shop.save()
    shop = Shop(name = "GELATO Firma handlowo-usługowa Aleksandra i Andrzej Adamowicz", type = "Hurtownia", product = "Artykuły spożywcze", address = "Reblinko 1, 76-251 Reblinko", phone = "(59) 841 55 22", email = "gelato.slupsk@zielonabudka.pl", website = "-", toggle = "manual", latitude = 54.441748, longitude = 16.934438, accuracy=250)
    shop.save()
    shop = Shop(name = "Gospodarstwo Sadownicze Karnicki", type = "Lokalny producent", product = "Winogrona", address = "Głobino 34, 76-200 Głobino", phone = "(59) 847 10 97, 606 213 641, 664 199 641, 664 948 180", email = "-", website = "-", toggle = "manual", latitude = 54.431537, longitude = 17.115734, accuracy=250)
    shop.save()
    shop = Shop(name = "HUBART Ubojnia Drobiu", type = "Hurtownia", product = "Drób ", address = "Bruskowo Wielkie 24, 76-200 Bruskowo Wielkie", phone = "(59) 846 15 31, 609 846 111", email = "puhhubart@poczta.onet.pl", website = "http://ubojnia-hubart.pl/", toggle = "manual", latitude = 54.495649, longitude = 16.906770, accuracy=250)
    shop.save()
    shop = Shop(name = "Hurtownia Drobiu i Mięsa Igliński Marek", type = "Hurtownia", product = "Drób ", address = "Przemysłowa 35, 76-200 Słupsk", phone = "(59) 842 87 71", email = "-", website = "-", toggle = "manual", latitude = 54.45097, longitude = 17.010242, accuracy=250)
    shop.save()
    shop = Shop(name = "Hurtownia spożywcza Łyszyk Anna", type = "Hurtownia", product = "Artykuły spożywcze", address = "M. C. Skłodowskiej 3, 76-200 Słupsk", phone = "(59) 842 92 44, 515 188 329", email = "-", website = "-", toggle = "manual", latitude = 54.467992, longitude = 17.039355, accuracy=250)
    shop.save()
    shop = Shop(name = "JANCZAR", type = "Hurtownia", product = "Owoce, warzywa", address = "Witolda Lutosławskiego 18, 76-200 Słupsk", phone = "(59) 842 29 10", email = "-", website = "-", toggle = "manual", latitude = 54.458251, longitude = 17.026484, accuracy=250)
    shop.save()
    shop = Shop(name = "JANCZAR Przedsiębiorstwo produkcyjno-usługowe", type = "Hurtownia", product = "Artykuły spożywcze", address = "Karola Szymanowskiego 18, 76-200 Słupsk", phone = "-", email = "-", website = "-", toggle = "manual", latitude = 54.457626, longitude = 17.028306, accuracy=250)
    shop.save()
    shop = Shop(name = "LEWNA piekarnia i cukiernia", type = "Piekarnia", product = "Chleb i wypieki", address = "Sierpinka 2, 76-200 Słupsk", phone = "(59) 842 82 76", email = "-", website = "-", toggle = "manual", latitude = 54.465434, longitude = 17.042003, accuracy=250)
    shop.save()
    shop = Shop(name = "MEAT-POL Hurtownia mięsa, wędlin i drobiu Jarosław Żuk", type = "Hurtownia", product = "Drób ", address = "Poznańska 42, 76-200 Słupsk", phone = "(59) 842 69 94", email = "-", website = "-", toggle = "manual", latitude = 54.449157, longitude = 17.010878, accuracy=250)
    shop.save()
    shop = Shop(name = "PASIEKA Karolczak", type = "Lokalny producent", product = "Miód", address = "Gdańska 76, 76-100 Sławno", phone = "509 198 311", email = "monikakarolczak@wp.pl", website = "-", toggle = "manual", latitude = 54.363433, longitude = 16.702027, accuracy=250)
    shop.save()
    shop = Shop(name = "PIEKIEŁKO Przedsiębiorstwo Produkcyjno Handlowo Usługowe Marek Powałka", type = "Hurtownia", product = "Mięso i produkty mięsne", address = "Przemysłowa 128, 76-200 Słupsk", phone = "(59) 840 04 10", email = "-", website = "-", toggle = "manual", latitude = 54.462489, longitude = 17.021305, accuracy=250)
    shop.save()
    shop = Shop(name = "PROSIACZEK Hurtownia wędlin, mięsa i drobiu", type = "Hurtownia", product = "Drób ", address = "Bałtycka 32, 76-200 Słupsk", phone = "(59) 842 82 67", email = "prosiaczekslupsk@interia.pl", website = "https://prosiaczek.indexfirm.pl/", toggle = "manual", latitude = 54.473562, longitude = 17.027350, accuracy=250)
    shop.save()
    shop = Shop(name = "SERKOL Hurtownia spożywczo-nabiałowa", type = "Hurtownia", product = "Nabiał", address = "Poznańska 42, 76-200 Słupsk", phone = "(59) 842 37 38", email = "serkolwyso@op.pl", website = "-", toggle = "manual", latitude = 54.449255, longitude = 17.011619, accuracy=250)
    shop.save()
    shop = Shop(name = "U JANUSZA Hurtownia Wędlin, Mięs i Drobiu", type = "Hurtownia", product = "Drób ", address = "Przemysłowa 35, 76-200 Słupsk", phone = "-", email = "-", website = "http://ujanusza.slupsk.pl/", toggle = "manual", latitude = 54.451112, longitude = 17.010336, accuracy=250)
    shop.save()
    shop = Shop(name = "UST-RYB", type = "Hurtownia", product = "Ryba", address = "Bohaterów Westerplatte 38, 76-270 Ustka", phone = "(59) 815 20 51, (59) 814 58 78", email = "biuro@ustryb.pl, ustryb@op.pl", website = "http://www.ust-ryb.com.pl/", toggle = "manual", latitude = 54.584499, longitude = 16.851991, accuracy=250)
    shop.save()
    shop = Shop(name = "Z JARACZA piekarnia i cukiernia", type = "Piekarnia", product = "Chleb i wypieki", address = "Stefana Jaracza 12, 76-200 Słupsk", phone = "508 355 883, 509 264 970", email = "biuro@zjaracza.pl", website = "http://www.zjaracza.pl/", toggle = "manual", latitude = 54.461856, longitude = 17.028695, accuracy=250)
    shop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
