# Generated by Django 2.2.3 on 2020-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200221_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='kindergarten_supplier',
            field=models.CharField(blank=True, choices=[('yes_en', 'Yes'), ('no_en', 'No'), ('yes_pl', 'Tak'), ('no_pl', 'Nie')], max_length=3, null=True, verbose_name='Do kindergartens buy from here?'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='toggle',
            field=models.CharField(blank=True, choices=[('gps_en', 'Use GPS'), ('interactive_en', 'Point on Map'), ('manual_en', 'Enter Manually'), ('gps_pl', 'Użyj GPS'), ('interactive_pl', 'Wybierz punkt na mapie'), ('manual_pl', 'Wprowadzić ręcznie')], max_length=11, null=True, verbose_name='Location Mode'),
        ),
    ]
