# Generated by Django 2.2.3 on 2019-08-22 12:10

from django.db import migrations

def insertData(apps, schema_editor):
     Kindergarten = apps.get_model('kindergarten', 'Kindergarten')
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 1 Zaczarowany Ogród", adress = "Kilińskiego 33, 76-200 Słupsk", latitude = 54.471523, longitude = 17.036565, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 2", adress = "Zamkowa 6, 76-200 Słupsk", latitude = 54.462979, longitude = 17.034063, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 3", adress = "Zygmunta Augusta 62a, 76-200 Słupsk", latitude = 54.467653, longitude = 16.999942, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 4 Królestwo Skrzatów", adress = "Lutosławskiego 6, 76-200 Słupsk", latitude = 54.459275, longitude = 17.027969, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 5", adress = "Juliana Nimcewicza 9, 76-200 Słupsk", latitude = 54.474074, longitude = 17.021958, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 6", adress = "Wandy 3, 76-200 Słupsk", latitude = 54.47072, longitude = 17.03052, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 7", adress = "Wileńska 2 , 76-200 Słupsk", latitude = 54.465283, longitude = 17.020263, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie Integracyjne nr 8", adress = "Wiatraczna 10, 76-200 Słupsk", latitude = 54.47794, longitude = 17.000978, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 9 Akademia Uśmiechu", adress = "Sportowa 10, 76-200 Słupsk", latitude = 54.479068, longitude = 17.041956, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 10 Świat Fantazji", adress = "Zygmunta Augusta 10 , 76-200 Słupsk", latitude = 54.466684, longitude = 17.00794, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 11 Calineczka", adress = "Kosynierów Gdyńskich 6, 76-200 Słupsk", latitude = 54.457017, longitude = 17.057623, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 12 Niezapominajka", adress = "Koszalińska 9, 76-200 Słupsk", latitude = 54.456091, longitude = 16.996595, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 15", adress = "Wiatraczna 6, 76-200 Słupsk", latitude = 54.476456, longitude = 17.005227, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 19 Słupskiego Chłopczyka", adress = "Norwida 4, 76-200 Słupsk", latitude = 54.464423, longitude = 16.994943, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 23 Promyczek", adress = "Wazów 1 , 76-200 Słupsk", latitude = 4.473277, longitude = 17.006214, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 24 Słupski Niedźwiadek Szczęścia", adress = "3 Maja 15 , 76-200 Słupsk", latitude = 54.474262, longitude = 17.011342, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 31 Bajkowa Kraina", adress = "Witosa 1, 76-200 Słupsk", latitude = 54.461292, longitude = 16.983678, accuracy=150)
     kindergarten.save()
     kindergarten = Kindergarten(name = "Przedszkole Miejskie Integracyjne nr 32 Tęczowa Kraina", adress = "Kasztanowa 1 , 76-200 Słupsk", latitude = 54.457117, longitude = 17.052988, accuracy=150)
     kindergarten.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
