# Generated by Django 2.2.3 on 2020-10-28 14:47

from django.db import migrations

def insertData(apps, schema_editor):
     Kindergarten = apps.get_model('kindergarten', 'Kindergarten')
     kindergarten = Kindergarten(name = "Przedszkole Miejskie nr 25 im. Kubusia Puchatka", address = "Powstańców Wielkopolskich 1, 76-200 Słupsk", toggle = "manual", latitude = 54.459513, longitude = 16.978607, accuracy=150)
     kindergarten.save() 

class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0002_auto_20190822_1210'),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
