# Generated by Django 2.2.3 on 2020-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0006_auto_20201110_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindergarten',
            name='toggle',
            field=models.CharField(blank=True, choices=[('gps_en', 'Use GPS'), ('interactive_en', 'Point on Map'), ('manual_en', 'Enter Manually'), ('gps_pl', 'Użyj GPS'), ('interactive_pl', 'Wybierz punkt na mapie'), ('manual_pl', 'Wprowadzić ręcznie')], max_length=11, null=True, verbose_name='Location Mode'),
        ),
    ]
