# Generated by Django 2.2.3 on 2020-12-02 15:20

from django.db import migrations

def updateData(apps, schema_editor):
     Kindergarten = apps.get_model('kindergarten', 'Kindergarten')

     kindergarten = Kindergarten.objects.get(name="Przedszkole Miejskie nr 12 Niezapominajka")
     kindergarten.facebook = "http://www.facebook.com/PM12niezapominajka"
     kindergarten.save()

     kindergarten = Kindergarten.objects.get(name="Przedszkole Miejskie nr 25 im. Kubusia Puchatka")
     kindergarten.website = "http://www.puchatek.slupsk.pl"
     kindergarten.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0008_auto_20201202_1327'),
    ]

    operations = [
        migrations.RunPython(updateData),
    ]
