# Generated by Django 2.2.3 on 2020-02-04 10:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0002_auto_20191217_1637'),
        ('shop', '0002_auto_20190822_1340'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_calculator', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Use the map to check the location of producers and to estimate the distance to a shop (see question below).')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.Producer', verbose_name='Producer')),
            ],
            options={
                'verbose_name': 'producerinfo',
                'verbose_name_plural': 'producerinfos',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Quantity (kg)')),
                ('frequency', models.TextField(blank=True, help_text='If you deliver this product regularly, please insert the delivery frequency, e.g. once per week.', null=True, verbose_name='Frequency')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price per item/kg (PLN)')),
                ('production_mode', models.CharField(blank=True, choices=[('organic_certificate', 'Organic with certificate'), ('organic_no_certificate', 'Organic without certificate'), ('traditional', 'Traditional'), ('industrial', 'Industrial')], max_length=22, null=True, verbose_name='Mode of production')),
                ('distance_to_shop', models.FloatField(blank=True, help_text='To calculate the distance you can use the line tool in the map above.', null=True, verbose_name='Distance to shop')),
                ('biodegradable_product', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('uncertain', 'Don&#x27;t know')], max_length=9, null=True, verbose_name='Was it biodegradable?')),
                ('recyclable_product_package', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('uncertain', 'Don&#x27;t know')], max_length=9, null=True, verbose_name='Was it in recycling packages?')),
                ('producerinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverys', to='producerinfo.Producerinfo')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredient.Ingredient', verbose_name='Product delivered')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='Shop delivered')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'deliverys',
            },
        ),
    ]
