# Generated by Django 2.2.3 on 2020-02-21 14:39

from django.db import migrations

def insertData(apps, schema_editor):
    Producer = apps.get_model('producer', 'Producer')
    producer = Producer(name = "Gospodarstwo Sadownicze Karnicki", type = "Winegrower", product = "Grapes", address = "Głobino 34, 76-200 Głobino", phone = "(59) 847 10 97, 606 213 641, 664 199 641, 664 948 180", email = "-", website = "-", toggle = "Enter Manually", latitude = 54.431643, longitude = 17.116031, accuracy=250)
    producer.save()
    producer = Producer(name = "PASIEKA Karolczak", type = "Beekeeper", product = "Honey", address = "Gdańska 76, 76-100 Sławno", phone = "509 198 311", email = "monikakarolczak@wp.pl", website = "-", toggle = "Enter Manually", latitude = 54.363335, longitude = 16.702279, accuracy=250)
    producer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
