# Generated by Django 2.2.3 on 2019-08-22 13:40

from django.db import migrations

def insertData(apps, schema_editor):
     Producer = apps.get_model('producer', 'Producer')
     producer = Producer(name = "Gospodarstwo sadownicze Feliks Karnicki", adress = "Głobino 34, 76-200 Słupsk", latitude = 54.431537, longitude = 17.115734, accuracy=250)
     producer.save()
     producer = Producer(name = "Hurtownia Warzyw i Owoców „Oranges” Sp.j.  M i M.", adress = "Ul. Lutosławskiego 18-19, 76-200 Słupsk", latitude = 54.458246, longitude = 17.02672, accuracy=250)
     producer.save()
     producer = Producer(name = "Punkt Skupu i sprzedaż hurtowa Ryb „ALGA” Karol Szcześniak", adress = "Ul. Grunwaldzka 12/60, 76-200 Ustka", latitude = 54.575949, longitude = 16.877038, accuracy=250)
     producer.save()
     producer = Producer(name = "Hurtownia Nabiałowo-Spożywcza „Serkol” Sp.J. Trynieccy", adress = "Ul. Poznańska 42, 76-200 Słupsk", latitude = 54.449255, longitude = 17.011619, accuracy=250)
     producer.save()
     producer = Producer(name = "Przedsiębiorstwo Handlowe „ANMAR” Spółka Cywilna Wioletta i Czesław Kazimierczak", adress = "Ul Lutosławskiego 18-19, 76-200 Słupsk", latitude = 54.458307, longitude = 17.02682, accuracy=250)
     producer.save()
     producer = Producer(name = "Boks Handlowy nr 60 Piotr Dymyter", adress = "Bazar na ulicy Banacha, 76-200 Słupsk", latitude = 54.469731, longitude = 17.00425, accuracy=250)
     producer.save()
     producer = Producer(name = "Gospodarstwo Rolne Jolanta Szmichowska’s", adress = "Ul. Sportowa 53, 76-200 Słupsk", latitude = 54.482612, longitude = 17.046469, accuracy=250)
     producer.save()
     producer = Producer(name = "Gospodarstwo rolne Marian Wojciechowski", adress = "Pałówko 54, 76-113 Postomino", latitude = 54.437958, longitude = 16.826447, accuracy=250)
     producer.save()
     producer = Producer(name = "Ust-RYB Ustka Henryk Padewski", adress = "Ul. Westerplatte 38, 76-270 Ustka", latitude = 54.584499, longitude = 16.851991, accuracy=250)
     producer.save()
     producer = Producer(name = "Piekarnia LEWNA", adress = "Ul. Sierpinka 2, 76-200 Słupsk", latitude = 54.465434, longitude = 17.042003, accuracy=250)
     producer.save()
     producer = Producer(name = "U Janusza", adress = "Ul. Przemysłowa 35, 76-200 Słupsk", latitude = 54.451112, longitude = 17.010336, accuracy=250)
     producer.save()
     producer = Producer(name = "Hurtownia drobiu i mięsa z rozbiorem Marek Igliński", adress = "Ul. Przemysłowa 35, 76-200 Słupsk", latitude = 54.45097, longitude = 17.010242, accuracy=250)
     producer.save()
     producer = Producer(name = "Piekarnia „ROGALIK”", adress = "Ul. Długa 19, 76-200 Słupsk", latitude = 54.461413, longitude = 17.027077, accuracy=250)
     producer.save()
     producer = Producer(name = "Ubojnia drobiu „HUBART” Piotr i Maria Powęzka", adress = "Ul. Bruskowo Wielkie 24, 76-206 Słupsk", latitude = 54.495649, longitude = 16.90677, accuracy=250)
     producer.save()
     producer = Producer(name = "Hurtownia „PROSIACZEK”", adress = "Ul. Bałtycka 32, 76-200 Słupsk", latitude = 54.473549, longitude = 17.027718, accuracy=250)
     producer.save()
     producer = Producer(name = "FAMILY - ICE", adress = "Ul. Wodna 15, 76-251 Kobylnica", latitude = 54.440167, longitude = 17.015746, accuracy=250)
     producer.save()
     producer = Producer(name = "FHU „GELATO” A.A.Adamowicz", adress = "76-256 Reblinko 1", latitude = 54.441748, longitude = 16.934438, accuracy=250)
     producer.save()
     producer = Producer(name = "Sklep rybny „Delfin” J.Michałkiewicz", adress = "Ul. Wolności 110, 76-200 Słupsk", latitude = 54.47067, longitude = 17.026779, accuracy=250)
     producer.save()
     producer = Producer(name = "Ferma kur ADKONIS", adress = "Ul. Słupska 1, 76-251 Kwakowo", latitude = 54.370454, longitude = 17.022231, accuracy=250)
     producer.save()
     producer = Producer(name = "Zakład Piekarniczo-Ciastkarski „SPOŁEM”", adress = "Ul. Polanowska 45, 76-100 Sławno", latitude = 54.349536, longitude = 16.680857, accuracy=250)
     producer.save()
     producer = Producer(name = "Rolnik Sitkowski Zenon", adress = "Grobkowo 26, 76-242 Łupawa", latitude = 54.421435, longitude = 17.421833, accuracy=250)
     producer.save()
     producer = Producer(name = "Piekarnia „DOMIN”", adress = "Ul. Kościelna 33, 76-248 Dębnica Kaszubska", latitude = 54.375193, longitude = 17.158957, accuracy=250)
     producer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
