# Generated by Django 2.2.3 on 2020-12-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20201202_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='kindergarten_supplier',
            field=models.CharField(blank=True, choices=[('yes_en', 'Yes'), ('no_en', 'No'), ('yes_pl', 'Tak'), ('no_pl', 'Nie')], max_length=6, null=True, verbose_name='Do kindergartens use products from here?'),
        ),
    ]
