# Generated by Django 2.2.3 on 2021-07-13 14:34

from django.db import migrations
from django.contrib.gis.geos import Point


def updateData(apps, schema_editor):
    Producer = apps.get_model('producer', 'Producer')

    producer = Producer.objects.get(name="Gospodarstwo Sadownicze Karnicki")
    producer.geometry = Point(producer.longitude, producer.latitude)
    producer.save()

    producer = Producer.objects.get(name="PASIEKA Karolczak")
    producer.geometry = Point(producer.longitude, producer.latitude)
    producer.save()


class Migration(migrations.Migration):
    dependencies = [
        ('producer', '0005_auto_20201202_1407'),
    ]

    operations = [
        migrations.RunPython(updateData),
    ]
