# Generated by Django 2.2.3 on 2019-08-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantitty',
            new_name='quantity',
        ),
    ]
