# Generated by Django 2.2.3 on 2020-02-21 13:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0002_auto_20191217_1637'),
        ('shop', '0002_auto_20200221_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privatedish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Enter the name of the dish')),
                ('ingredient_list', models.TextField(blank=True, help_text='Please enter the name of the ingredients separated by a comma.', null=True, verbose_name='Ingredients')),
                ('distance_calculator', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Use the line tool in the map to estimate the distance.')),
            ],
            options={
                'verbose_name': 'privatedish',
                'verbose_name_plural': 'privatedishs',
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, choices=[('local', 'Local'), ('non_local', 'Non-local')], max_length=9, null=True, verbose_name='Enter the place of origin')),
                ('production_mode', models.CharField(blank=True, choices=[('organic_certificate', 'Organic with certificate'), ('organic_no_certificate', 'Organic without certificate'), ('traditional', 'Traditional'), ('industrial', 'Industrial')], max_length=22, null=True, verbose_name='Enter the mode of production')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Enter the price')),
                ('from_producer', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True, verbose_name='Was the ingredient bought directly from the producer?')),
                ('distance', models.FloatField(blank=True, help_text='You can use the line tool in the map below to estimate the distance.', null=True, verbose_name='Enter the distance (km) from the shop to your house if bought in a shop. If bought directly from the producer, enter the distance (km) from the producer to your house.')),
                ('satisfaction', models.CharField(blank=True, choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], help_text='(1 = „it was awful&quot;, 5 = „it was delicious&quot;)', max_length=5, null=True, verbose_name='Did you like it?')),
                ('health', models.CharField(blank=True, choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], help_text='(1 = „it is very bad for my health&quot;, 5 = „it is very healthy&quot;)', max_length=5, null=True, verbose_name='Do you think it is healthy?')),
                ('quality', models.CharField(blank=True, choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], help_text='(1 = „bad quality&quot;, 5 = „high quality&quot;)', max_length=5, null=True, verbose_name='Do you think it is a high quality product?')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privatedish_ingredient', to='ingredient.Ingredient', verbose_name='Ingredient')),
                ('privatedish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='privatedish.Privatedish')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privatedish_shop', to='shop.Shop', verbose_name='Where was it bought?')),
            ],
            options={
                'verbose_name': 'composition',
                'verbose_name_plural': 'compositions',
            },
        ),
    ]
