# Generated by Django 2.2.3 on 2020-07-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producer', '0002_auto_20200221_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privatedish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=False, null=False, verbose_name='Enter the name of the dish')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='privatedishs', verbose_name='Picture of the dish')),
                ('from_producer', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True, verbose_name='Did you buy at least one ingredient from a local producer?')),
            ],
            options={
                'verbose_name': 'privatedish',
                'verbose_name_plural': 'privatedishs',
            },
        ),
        migrations.CreateModel(
            name='Localproducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privatedish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localproducers', to='privatedish.Privatedish')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privatedish_producer', to='producer.Producer', verbose_name='From which local producer did you buy an ingredient?')),
            ],
            options={
                'verbose_name': 'localproducer',
                'verbose_name_plural': 'localproducers',
            },
        ),
    ]
