# Generated by Django 2.2.3 on 2019-08-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindergarten', '0001_initial'),
        ('shop', '0001_initial'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name of dish')),
                ('kindergarten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kindergarten.Kindergarten', verbose_name='Kindergarten')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dishes', verbose_name='Photo')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dish.Dish')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_gram', models.FloatField(blank=True, null=True, verbose_name='Quantity (in grams)')),
                ('origin', models.CharField(blank=True, choices=[('local', 'Local'), ('regional', 'Regional'), ('global', 'Global')], max_length=8, null=True, verbose_name='Place of origin')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='dish.Dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.Ingredient', verbose_name='Ingredient')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='Shop')),
            ],
            options={
                'verbose_name': 'composition',
                'verbose_name_plural': 'compositions',
            },
        ),
    ]
