# Generated by Django 2.2.3 on 2019-09-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(blank=True, choices=[('institutional', 'Institutional'), ('private', 'Private')], max_length=13, null=True, verbose_name='Type of dish'),
        ),
    ]
