# Generated by Django 2.2.3 on 2019-12-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredient', to='ingredient.Ingredient', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='kindergarten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_kindergarten', to='kindergarten.Kindergarten', verbose_name='Kindergarten'),
        ),
    ]
